[pi-day]
title = "Celebrate Pi Day"
experiences = [ "pi", "pi-circle", "pi-walk", "pi-triangle" ]

[interactive]
title = "Interactive Experiences"
experiences = [
  "mirror-of-whimsy",
  "ai-artist",
  "ifs",
  "hilbert",
  "wind",
  "life",
  "stylegan",
  "style-transfer",
  "fluid",
  "pong4",
  "your-campus",
  "sorting",
  "fractals",
  "butterfly",
  "maze-generation",
  "bus-bunching"
]

[game]
title = "BYU Games"
experiences = [ "liminus", "brawlers", "beatboxers", "neokaiju", "avastye" ]

[animation]
title = "BYU Animation"
experiences = [
  "taijitu",
  "grendel",
  "death",
  "estefan",
  "metro",
  "owned",
  "papa",
  "rams-horn",
  "salt",
  "stowaway",
  "cenote",
  "witchscat",
  "studacc"
]

[graduation]
title = "Graduation"
experiences = [
  "graduation",
  "photo-op"
]

[cpms50]
title = "CPMS is 50"
experiences = [ "cpms50" ]

[lds]
title = "LDS-themed experiences"
experiences = [
  "temple-photo-op"
]
